import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';
import { jsPDF } from 'npm:jspdf@4.0.0';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { lead_id, photos = [], notes = '', estimated_repairs = null } = await req.json();

    if (!lead_id) {
      return Response.json({ error: 'Missing lead_id' }, { status: 400 });
    }

    // Fetch lead and property data
    const leads = await base44.entities.Lead.filter({ id: lead_id });
    const lead = leads?.[0];

    if (!lead) {
      return Response.json({ error: 'Lead not found' }, { status: 404 });
    }

    const propertyDataList = await base44.entities.PropertyData.filter({ lead_id });
    const propertyData = propertyDataList?.[0];

    // Create PDF
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let yPos = 15;

    // Header
    doc.setFontSize(18);
    doc.setFont(undefined, "bold");
    doc.text("PROPERTY INSPECTION REPORT", pageWidth / 2, yPos, { align: "center" });
    yPos += 12;

    // Report date and inspector
    doc.setFontSize(10);
    doc.setFont(undefined, "normal");
    doc.text(`Inspection Date: ${new Date().toLocaleDateString()}`, 20, yPos);
    yPos += 5;
    doc.text(`Inspector: ${user.full_name}`, 20, yPos);
    yPos += 8;

    // Property Information
    doc.setFontSize(12);
    doc.setFont(undefined, "bold");
    doc.text("PROPERTY INFORMATION", 20, yPos);
    yPos += 6;

    doc.setFontSize(10);
    doc.setFont(undefined, "normal");
    const propertyInfo = [
      `Address: ${lead.property_address}`,
      `City, State, ZIP: ${lead.city}, ${lead.state} ${lead.zip_code}`,
      ...(propertyData?.bedrooms ? [`Bedrooms: ${propertyData.bedrooms}`] : []),
      ...(propertyData?.bathrooms ? [`Bathrooms: ${propertyData.bathrooms}`] : []),
      ...(propertyData?.square_footage ? [`Square Footage: ${propertyData.square_footage.toLocaleString()}`] : []),
      ...(propertyData?.year_built ? [`Year Built: ${propertyData.year_built}`] : []),
    ];

    propertyInfo.forEach((info) => {
      doc.text(info, 25, yPos);
      yPos += 5;
    });

    yPos += 3;

    // Photos Section
    if (photos.length > 0) {
      doc.setFontSize(12);
      doc.setFont(undefined, "bold");
      doc.text(`INSPECTION PHOTOS (${photos.length})`, 20, yPos);
      yPos += 8;

      // Add photos (max 2 per row)
      let photoCount = 0;
      for (let i = 0; i < photos.length; i += 2) {
        // Check if we need a new page
        if (yPos > pageHeight - 100) {
          doc.addPage();
          yPos = 15;
        }

        // First photo
        if (photos[i]) {
          const imgData = photos[i];
          doc.addImage(imgData, "JPEG", 20, yPos, 80, 60);
          photoCount++;
        }

        // Second photo (if exists)
        if (photos[i + 1]) {
          const imgData = photos[i + 1];
          doc.addImage(imgData, "JPEG", 110, yPos, 80, 60);
          photoCount++;
        }

        yPos += 65;
      }

      yPos += 3;
    }

    // Check if we need a new page
    if (yPos > pageHeight - 80) {
      doc.addPage();
      yPos = 15;
    }

    // Inspection Notes
    if (notes.trim()) {
      doc.setFontSize(12);
      doc.setFont(undefined, "bold");
      doc.text("INSPECTION NOTES", 20, yPos);
      yPos += 6;

      doc.setFontSize(10);
      doc.setFont(undefined, "normal");
      const notesLines = doc.splitTextToSize(notes, 170);
      doc.text(notesLines, 25, yPos);
      yPos += notesLines.length * 5 + 3;
    }

    yPos += 3;

    // Repair Estimates Section
    if (estimated_repairs !== null && estimated_repairs !== undefined) {
      doc.setFontSize(12);
      doc.setFont(undefined, "bold");
      doc.text("REPAIR ESTIMATES", 20, yPos);
      yPos += 6;

      doc.setFontSize(11);
      doc.setFont(undefined, "bold");
      doc.text(`Estimated Repair Costs: $${estimated_repairs.toLocaleString()}`, 25, yPos);
      yPos += 8;

      // Summary box
      doc.setFont(undefined, "normal");
      doc.setFontSize(9);
      doc.setFillColor(240, 240, 240);
      doc.rect(20, yPos, 170, 15, "F");
      doc.text(
        "These estimated costs should be reviewed and refined based on detailed contractor quotes.",
        25,
        yPos + 5
      );
      yPos += 18;
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text(
      `Generated by Deal Mentor on ${new Date().toLocaleString()}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );

    // Generate PDF as data URL
    const pdfData = doc.output("dataurlstring");

    // Update property data with repair costs if provided
    if (estimated_repairs !== null && estimated_repairs !== undefined && propertyData) {
      await base44.entities.PropertyData.update(propertyData.id, {
        estimated_repairs,
      });
    }

    // Create document record
    const document = await base44.entities.Document.create({
      lead_id,
      document_name: `Inspection Report - ${new Date().toLocaleDateString()}`,
      document_type: "Inspection Report",
      file_url: pdfData,
      notes: notes || null,
    });

    return Response.json({
      success: true,
      pdf_data: pdfData,
      document_id: document.id,
      filename: `inspection_report_${lead.property_address?.replace(/\s+/g, "_")}.pdf`,
      repair_costs_updated: !!estimated_repairs,
    });
  } catch (error) {
    console.error("Error generating inspection report:", error);
    return Response.json(
      { error: error.message || "Failed to generate inspection report" },
      { status: 500 }
    );
  }
});